### ISSUE TITLE
Bot gets booted by BotDefense

### ISSUE THREAD

**Issue by raspimana** [eganwall/FatFingerHelperBot#1]
Just happened to my on my subreddit. I know a _bit_ of python, but it's currently 1 in the morning and I am fighting the urge to sleep, with my phone, in bed.

Here's a possible fix: Add a cool down (5 minutes?) on subreddits with u/BotDefense as a moderator.

**Comment by FormerlyChucks** [comment]
Or maybe don't spam reddit?

**Comment by eganwall** [comment]
The plan in the near future is to transition the bot to come when called, which should avoid any spam issues. Looking at my current metrics, the bot doesn't post a whole lot - in the last 6 hours, it's posted 130 comment replies which is obviously more than an average human but I wouldn't really consider ~22 comments per hour across the entire Reddit ecosystem to be spam.
